# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Create a non-root user and switch to that user
RUN useradd -m sandboxuser

# Set the working directory in the container
WORKDIR /app 

# Install basic tools
RUN pip install --no-cache-dir fastapi uvicorn

#Switch Non root user
USER sandboxuser


CMD [ "sleep" , "infinity"]