from fastapi import FastAPI, Request
import time

app = FastAPI()

# 1️⃣ Logger Middleware
@app.middleware("http")
async def logger_middleware(request: Request, call_next):
    start_time = time.time()

    print(f"[LOGGER] Incoming: {request.method} {request.url.path}")

    response = await call_next(request) # Call the next middleware or route handler

    process_time = time.time() - start_time # calculate processing time asynchronously
    print(f"[LOGGER] Completed in {process_time:.4f}s")

    return response # Return the response to the client what is response in this context? response is the result of call_next(request) which is the response generated by the next middleware or route handler in the chain. It represents the HTTP response that will be sent back to the client after all middleware and route handlers have processed the request.


# 2️⃣ Route + Method Middleware
@app.middleware("http")
async def route_info_middleware(request: Request, call_next):
    print(f"You are on route: {request.url.path} and method: {request.method}")

    response = await call_next(request)
    return response


@app.get("/")
async def home():
    return {"message": "Home route"}

@app.post("/create")
async def create_item():
    return {"message": "POST route"}
