#pull the base image 
FROM python:3.11-slim

# set the working directory in the container
WORKDIR /app

# # copy the dependencies file to the working directory 
# COPY requirements.txt .
# Copy project files
COPY . /app

# 4. Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn

# 5. Expose FastAPI port
EXPOSE 8000

# 6. Start FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]